// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	models "github.com/Seven11Eleven/auth_service_medods/internal/auth/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// JWTUtils is an autogenerated mock type for the JWTUtils type
type JWTUtils struct {
	mock.Mock
}

// CreateAccessToken provides a mock function with given fields: user, expired
func (_m *JWTUtils) CreateAccessToken(user *models.User, expired int) (string, error) {
	ret := _m.Called(user, expired)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccessToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.User, int) (string, error)); ok {
		return rf(user, expired)
	}
	if rf, ok := ret.Get(0).(func(*models.User, int) string); ok {
		r0 = rf(user, expired)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*models.User, int) error); ok {
		r1 = rf(user, expired)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateRefreshToken provides a mock function with given fields: user, expired
func (_m *JWTUtils) CreateRefreshToken(user *models.User, expired int) (string, error) {
	ret := _m.Called(user, expired)

	if len(ret) == 0 {
		panic("no return value specified for CreateRefreshToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.User, int) (string, error)); ok {
		return rf(user, expired)
	}
	if rf, ok := ret.Get(0).(func(*models.User, int) string); ok {
		r0 = rf(user, expired)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*models.User, int) error); ok {
		r1 = rf(user, expired)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExtractEmailFromRefreshToken provides a mock function with given fields: originalToken
func (_m *JWTUtils) ExtractEmailFromRefreshToken(originalToken string) (string, error) {
	ret := _m.Called(originalToken)

	if len(ret) == 0 {
		panic("no return value specified for ExtractEmailFromRefreshToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(originalToken)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(originalToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(originalToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExtractIDFromToken provides a mock function with given fields: requestedToken
func (_m *JWTUtils) ExtractIDFromToken(requestedToken string) (uuid.UUID, error) {
	ret := _m.Called(requestedToken)

	if len(ret) == 0 {
		panic("no return value specified for ExtractIDFromToken")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (uuid.UUID, error)); ok {
		return rf(requestedToken)
	}
	if rf, ok := ret.Get(0).(func(string) uuid.UUID); ok {
		r0 = rf(requestedToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(requestedToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExtractIPFromRefreshToken provides a mock function with given fields: email, originalToken
func (_m *JWTUtils) ExtractIPFromRefreshToken(email string, originalToken string) (string, error) {
	ret := _m.Called(email, originalToken)

	if len(ret) == 0 {
		panic("no return value specified for ExtractIPFromRefreshToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(email, originalToken)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(email, originalToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(email, originalToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsAuthorized provides a mock function with given fields: token
func (_m *JWTUtils) IsAuthorized(token string) (bool, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for IsAuthorized")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewJWTUtils creates a new instance of JWTUtils. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJWTUtils(t interface {
	mock.TestingT
	Cleanup(func())
}) *JWTUtils {
	mock := &JWTUtils{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
