// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/Seven11Eleven/auth_service_medods/internal/auth/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// RefreshTokenService is an autogenerated mock type for the RefreshTokenService type
type RefreshTokenService struct {
	mock.Mock
}

// CreateAccessToken provides a mock function with given fields: user, expired
func (_m *RefreshTokenService) CreateAccessToken(user *models.User, expired int) (string, error) {
	ret := _m.Called(user, expired)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccessToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.User, int) (string, error)); ok {
		return rf(user, expired)
	}
	if rf, ok := ret.Get(0).(func(*models.User, int) string); ok {
		r0 = rf(user, expired)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*models.User, int) error); ok {
		r1 = rf(user, expired)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateRefreshToken provides a mock function with given fields: user, expired
func (_m *RefreshTokenService) CreateRefreshToken(user *models.User, expired int) (string, error) {
	ret := _m.Called(user, expired)

	if len(ret) == 0 {
		panic("no return value specified for CreateRefreshToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.User, int) (string, error)); ok {
		return rf(user, expired)
	}
	if rf, ok := ret.Get(0).(func(*models.User, int) string); ok {
		r0 = rf(user, expired)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*models.User, int) error); ok {
		r1 = rf(user, expired)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExtractEmailFromRefreshToken provides a mock function with given fields: originalToken
func (_m *RefreshTokenService) ExtractEmailFromRefreshToken(originalToken string) (string, error) {
	ret := _m.Called(originalToken)

	if len(ret) == 0 {
		panic("no return value specified for ExtractEmailFromRefreshToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(originalToken)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(originalToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(originalToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExtractIDFromToken provides a mock function with given fields: requestedToken
func (_m *RefreshTokenService) ExtractIDFromToken(requestedToken string) (uuid.UUID, error) {
	ret := _m.Called(requestedToken)

	if len(ret) == 0 {
		panic("no return value specified for ExtractIDFromToken")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (uuid.UUID, error)); ok {
		return rf(requestedToken)
	}
	if rf, ok := ret.Get(0).(func(string) uuid.UUID); ok {
		r0 = rf(requestedToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(requestedToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExtractIPFromRefreshToken provides a mock function with given fields: token, originalToken
func (_m *RefreshTokenService) ExtractIPFromRefreshToken(token string, originalToken string) (string, error) {
	ret := _m.Called(token, originalToken)

	if len(ret) == 0 {
		panic("no return value specified for ExtractIPFromRefreshToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(token, originalToken)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(token, originalToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(token, originalToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *RefreshTokenService) GetUserByEmail(ctx context.Context, email string) (*models.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsAuthorized provides a mock function with given fields: token
func (_m *RefreshTokenService) IsAuthorized(token string) (bool, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for IsAuthorized")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRefreshTokenService creates a new instance of RefreshTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshTokenService {
	mock := &RefreshTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
